env:
  global:
    - secure: M/HmbF8k9maPj0JbbreweB/2cff+Khw+mU9HRHVB+K3LDjOuMRjqM4K5SegbEBTa04CIP59h40wWl3Z0OLW3Co/BqTBe6UiUfyPvM2rBdkm3BJcAbw2dJWR5wUv2635XgKJOz2hEtg63nAdO0L4zeyKrAoxUljGvKQksLlehBV8=
    - LibSodiumVersion=1.0.3
    - ElfUtilsVersion=0.163
    - Features=use-mock-routing
os:
  - linux
  - osx
language: rust
rust:
  - nightly
#  - beta
#  - stable
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - $HOME/libsodium-$LibSodiumVersion
    - $HOME/elfutils-$ElfUtilsVersion
install:
  - curl -sSLO https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/install_libsodium.sh
  - . install_libsodium.sh
script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/build_and_run_tests.sh | bash
  - cargo test --release -- --nocapture vault::test::network_test;
after_success:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/after_success.sh | bash
