environment:
  global:
    GH_TOKEN:
      secure: Plf6CbvLc5BWpB51EU9Sk/RMow47fZp74uSKt1Wv20kFRf1OQS2pVuEzgXQPuyhW
    PROJECT_NAME: safe_vault
    RUST_BACKTRACE: 1
  matrix:
    - RUST_VERSION: stable
branches:
  only:
    - master
    - 0.10

clone_depth: 50
skip_tags: true

cache:
  - '%USERPROFILE%\.cargo'
  - '%APPVEYOR_BUILD_FOLDER%\target'

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/Powershell%20Scripts/AppVeyor"
        Start-FileDownload "$url/Install%20Rustup.ps1" -FileName "Install Rustup.ps1"
        Start-FileDownload "$url/Build.ps1" -FileName "Build.ps1"
        Start-FileDownload "$url/Run%20Tests.ps1" -FileName "Run Tests.ps1"
        . ".\Install Rustup.ps1"

        $commit_message = "$env:APPVEYOR_REPO_COMMIT_MESSAGE $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"

        if ($commit_message -match "[vV]ersion change to v?(.*)") {
          $env:PROJECT_VERSION = $matches[1]
          $env:DEPLOY = "true"
        }

platform:
  - x86
  - x64

configuration:
  - Release

build_script:
  - ps: . ".\Build.ps1"

test_script:
  - ps: . ".\Run Tests.ps1"

before_deploy:
  - ps: . ".\ci\appveyor\before_deploy.ps1"

deploy:
  provider: GitHub
  auth_token: $(GH_TOKEN)
  # Deploy the archive (zip) and the installer (exe)
  artifact: /.*\.zip|.*\.exe/
  draft: true
  tag: $(PROJECT_VERSION)
  on:
    DEPLOY: true
    RUST_VERSION: stable
