environment:
  global:
    GH_TOKEN:
      # TODO Regenerate this auth_token for your project, this one won't work for you. Here's how:
      # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the
      # `public_repo` scope enabled
      # - Then go to 'https://ci.appveyor.com/tools/encrypt' and enter the newly generated token.
      # - Enter the "encrypted value" below
      secure: ipSdOqm+lOjEMrx4ABEQkxlQ/9x/aEmx0fRVqr7rC335sS24z+t/9/fFQKWBx3wV
    PROJECT_NAME: safe_vault
    RUST_BACKTRACE: 1
  matrix:
    - RUST_VERSION: stable
branches:
  only:
    - master

clone_depth: 50
skip_tags: true

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/Powershell%20Scripts/AppVeyor"
        Start-FileDownload "$url/Install%20Rust.ps1" -FileName "Install Rust.ps1"
        Start-FileDownload "$url/Install%20MinGW.ps1" -FileName "Install MinGW.ps1"
        Start-FileDownload "$url/Install%20libsodium.ps1" -FileName "Install libsodium.ps1"
        Start-FileDownload "$url/Build.ps1" -FileName "Build.ps1"
        Start-FileDownload "$url/Run%20Tests.ps1" -FileName "Run Tests.ps1"
        . ".\Install Rust.ps1"
        . ".\Install MinGW.ps1"
        . ".\Install libsodium.ps1"

        if ($env:APPVEYOR_REPO_COMMIT_MESSAGE -match "[vV]ersion change to v?(.*)") {
          $env:PROJECT_VERSION = $matches[1]
          $env:DEPLOY = "true"
        }

platform:
  - x86
  - x64

configuration:
  - Release

build_script:
  - ps: . ".\Build.ps1"

test_script:
  - ps: . ".\Run Tests.ps1"

before_deploy:
  - ps: . ".\ci\appveyor\before_deploy.ps1"

deploy:
  provider: GitHub
  auth_token: $(GH_TOKEN)
  # All the zipped artifacts will be deployed
  artifact: /.*\.zip/
  draft: true
  tag: $(PROJECT_VERSION)
  on:
    DEPLOY: true
    RUST_VERSION: stable
