environment:
  global:
    GH_TOKEN:
    # TODO: XXX
    #   secure: Plf6CbvLc5BWpB51EU9Sk/RMow47fZp74uSKt1Wv20kFRf1OQS2pVuEzgXQPuyhW
      secure: H46Isgt6cj7QSVGk1lGDbD5qudCe//5WprY2OA7hbTVUCjPe7dctJlbpLEK0uoUY

    # INSTALLER_CERT_SECRET:
    #   secure: GfkiZSo2sN4Hk8QgXca5HFcgYcw7eSGSa+XLklQb0WpLpEZbPnt83/umucg5EQz9xqouUN14WMOFlmfbgtXMgDZHsbNoN402ZFktN05Qn+U=

    PROJECT_NAME: safe_vault
    RUST_BACKTRACE: 1
  matrix:
    - RUST_VERSION: stable
branches:
  only:
    # TODO: XXX
    # - master
    - installer

clone_depth: 50
skip_tags: true

cache:
  - '%USERPROFILE%\.cargo'
  - '%APPVEYOR_BUILD_FOLDER%\target'

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/Powershell%20Scripts/AppVeyor"
        Start-FileDownload "$url/Install%20Rust.ps1" -FileName "Install Rust.ps1"
        Start-FileDownload "$url/Install%20MinGW.ps1" -FileName "Install MinGW.ps1"
        Start-FileDownload "$url/Install%20libsodium.ps1" -FileName "Install libsodium.ps1"
        Start-FileDownload "$url/Build.ps1" -FileName "Build.ps1"
        Start-FileDownload "$url/Run%20Tests.ps1" -FileName "Run Tests.ps1"
        . ".\Install Rust.ps1"
        . ".\Install MinGW.ps1"
        . ".\Install libsodium.ps1"

        if ($env:APPVEYOR_REPO_COMMIT_MESSAGE -match "[vV]ersion change to v?(.*)") {
          $env:PROJECT_VERSION = $matches[1]
          $env:DEPLOY = "true"
        }

platform:
  - x86
  - x64

configuration:
  - Release

build_script:
  - ps: echo "[Build script placeholder]"
# TODO: XXX
#   - ps: . ".\Build.ps1"

test_script:
  - ps: echo "[Test script placeholder]"
# TODO: XXX
#   - ps: . ".\Run Tests.ps1"

before_deploy:
  - ps: . ".\ci\appveyor\before_deploy.ps1"

deploy:
  provider: GitHub
  auth_token: $(GH_TOKEN)
  # Deploy the archive (zip) and the installer (exe)
  artifact: /.*\.zip|.*\.exe/
  draft: true
  tag: $(PROJECT_VERSION)
  on:
    DEPLOY: true
    RUST_VERSION: stable
