install:
  - ps: |
        Start-FileDownload "https://github.com/maidsafe/QA/raw/master/Powershell%20Scripts/InstallRust.ps1"; . .\InstallRust.ps1
        Start-FileDownload "https://github.com/maidsafe/QA/raw/master/Dependencies/Windows/$env:platform/libsodium.a";
        $env:SODIUM_LIB_DIR = Resolve-Path .

platform:
  - x86
  - x64

configuration:
#  - Debug
  - Release

environment:
  matrix:
#    - RUST_VERSION: 1.1.0
#    - RUST_VERSION: beta
    - RUST_VERSION: nightly

build: false

test_script:
  - ps: if ($env:CONFIGURATION -eq "Release") {
          $env:config_flags = "--release"
        }
  - cargo build --verbose --features "use-mock-routing" %config_flags%
  - cargo test --verbose --features "use-mock-routing" %config_flags%
  - cargo test %config_flags% -- --nocapture vault::test::network_test
