[package]
name = "safe_vault"
version = "0.2.0"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://maidsafe.net/safe_vault/latest"
repository = "https://github.com/maidsafe/safe_vault"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
cbor = "~0.3.16"
crust = "~0.7.0"
kademlia_routing_table = "~0.0.4"
log = "~0.3.4"
lru_time_cache = "~0.2.5"
maidsafe_utilities = "~0.1.5"
rand = "~0.3.12"
routing = "~0.5.1"
rustc-serialize = "~0.3.16"
sodiumoxide = "~0.0.9"
tempdir = "~0.3.4"
time = "~0.1.34"
xor_name = "~0.0.1"

[features]
use-mock-routing = []
