[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://maidsafe.net/safe_vault/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_vault"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_vault"
version = "0.5.0"
build = "build.rs"

[dependencies]
chunk_store = "~0.3.0"
clippy = {version = "~0.0.59", optional = true}
config_file_handler = "~0.3.0"
ctrlc = "~1.1.1"
docopt = "~0.6.78"
log = "~0.3.5"
maidsafe_utilities = "~0.5.0"
routing = "~0.12.0"
rustc-serialize = "~0.3.18"
safe_network_common = "~0.0.1"
sodiumoxide = "~0.0.9"
time = "~0.1.34"
xor_name = "~0.1.0"

[dev-dependencies]
kademlia_routing_table = "~0.4.0"
rand = "~0.3.14"
safe_core = "~0.13.0"

[build-dependencies]
hyper = "0.8.0"

[features]
use-mock-routing = []
use-mock-crust = ["routing/use-mock-crust", "safe_core/use-mock-crust"]
generate-diagrams = []

[[test]]
harness = false
name = "ci"
