[package]

name = "maidsafe_vault"
version = "0.0.1"
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://dirvine.github.io/maidsafe_vault/"
repository = "https://github.com/dirvine/maidsafe_vault"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
rustc-serialize = "*"
cbor = "*"
time = "*"
sodiumoxide = "*"
rand = "*"

[dependencies.bchannel]
git="https://github.com/dirvine/bchannel"

[dependencies.lru-cache]
git="https://github.com/contain-rs/lru-cache.git"

[dependencies.maidsafe_types]
git = "https://github.com/dirvine/maidsafe_types"

[dependencies.self_encryption]
git = "https://github.com/dirvine/self_encryption"

#[dependencies.utp]
#git = "https://github.com/meqif/rust-utp"

[dependencies.routing]
git = "https://github.com/dirvine/routing"
