[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://maidsafe.net/safe_vault/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_vault"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_vault"
version = "0.5.0"
build = "build.rs"

[dependencies]
chunk_store = "~0.3.0"
clippy = {version = "~0.0.62", optional = true}
config_file_handler = "~0.3.0"
ctrlc = "~1.1.1"
docopt = "~0.6.78"
log = "~0.3.6"
maidsafe_utilities = "~0.5.1"
routing = "~0.15.0"
rustc-serialize = "~0.3.19"
safe_network_common = "~0.1.1"
sodiumoxide = "~0.0.10"
time = "~0.1.35"
xor_name = "~0.1.0"
safe_core = {version = "~0.14.2", optional = true}

[dev-dependencies]
kademlia_routing_table = "~0.4.0"
rand = "~0.3.14"

[build-dependencies]
hyper = {version = "~0.8.0", optional = true}

[features]
generate-diagrams = ["hyper"]
use-mock-crust = ["routing/use-mock-crust"]


[[test]]
name = "mock_crust"

[[bin]]
name = "safe_vault"
doc = false
