closure_indent_style = "Visual"
expr_indent_style = "Tabbed"
fn_brace_style = "PreferSameLine"
ideal_width = 100
leeway = 20
max_width = 120
reorder_imports = true
report_fixme = "Always"
tab_spaces = 4
where_density = "Tall"
