# E2E workflow.
#
# Runs basic checks with the CLI + authenticator

name: E2E

on: pull_request

env:
  # Run all cargo commands with --verbose.
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1
  # Deny all compiler warnings.
  RUSTFLAGS: "-D warnings"
  NODE_COUNT: "11" # this is a single section
  # I've seen 30 nodes work on CI atm.
  SAFE_AUTH_PASSPHRASE: "x"
  SAFE_AUTH_PASSWORD: "y"

jobs:
  tests:
    name: E2E tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      # Install Rust and required components
      - uses: actions-rs/toolchain@v1
        name: Install Rust & required components
        with:
          profile: minimal
          toolchain: stable
          override: true


      # Cache.
      - name: Cargo cache registry, index and build
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}
      
      # If we need a custom CLI version (testing out new APIs/messages etc, we'll need to supply a modified script here I suppose)
      - name: Place Safe CLI
        run:  curl -so- https://sn-api.s3.amazonaws.com/install.sh | bash
     
      - run: ~/.safe/cli/safe -V
      - run: ~/.safe/cli/safe auth install

      - name: Check Safe Versions
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run : |
          echo $PATH
          ~/.safe/cli/safe -V
          ~/.safe/authd/sn_authd -V
          ~/.safe/cli/safe --version

      - name: Build launch local network
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - run: ./target/release/launch_network

      - run: ~/.safe/cli/safe auth restart

      # Our basic test: create an account
      - name: Create Account
        run: ~/.safe/cli/safe auth create --test-coins --for-cli

      - run: ~/.safe/cli/safe auth unlock --self-auth

      # TODO: Add more tests/scripts to run here (or use CLI tests directly somehow...)


      # TODO: Upload all logs as artifacts....
      - name: Node Logs
        run: |
          ls $HOME/.safe/node/local-test-network
          cat $HOME/.safe/node/local-test-network/sn-node-genesis/sn_node.log
        if: failure()

      - name: Authd Logs
        run: |
          ls $HOME/.safe/authd/
          cat $HOME/.safe/authd/logs/sn_authd.log
        if: failure()
