# PR workflow.
#
# Runs full suite of checks, with warnings treated as errors.

name: PR

on: pull_request

env:
  # Run all cargo commands with --verbose.
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: "full"
  # Deny all compiler warnings.
  RUSTFLAGS: "-D warnings"

jobs:
  clippy:
    name: Rustfmt-Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install Rust and required components
      - uses: actions-rs/toolchain@v1
        name: Install Rust & required components
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      # Cache
      - name: Cargo cache registry, index and build
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}
      
      # Check if the code is formatted correctly.
      - name: Check formatting
        run: cargo fmt --all -- --check

      # Run Clippy.
      - name: Clippy checks
        shell: bash
        run: ./scripts/clippy

  coverage:
    name: Code coverage check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install Rust
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      # Cache.
      - name: Cargo cache registry, index and build
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}
      
      # Run cargo tarpaulin & push result to coveralls.io
      - name: rust-tarpaulin code coverage check
        uses: actions-rs/tarpaulin@master
        with:
          args: '-v --release --out Lcov'
      - name: Push code coverage results to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: ./lcov.info
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2

      # Install Rust
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Cache.
      - name: Cargo cache registry, index and build
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Cargo build node
        uses: actions-rs/cargo@v1
        if: matrix.os != 'macos-latest'
        with:
          command: build
          args: --release  --features=simulated-payouts

      # TODO: update for _node_ once we have SNLT updated
      - name: Copy node bin to correct location
        run: cp target/release/safe_vault ~/.safe/vault


      - name: Download Safe CLI Linux
        if: matrix.os == 'ubuntu-latest'
        run: wget "https://github.com/maidsafe/safe-api/releases/download/${{env.SAFE_CLI_VERSION}}/safe-cli-${{env.SAFE_CLI_VERSION}}-x86_64-unknown-linux-gnu.tar.gz" -O ./safe.tar.gz;

      - name: Download Safe CLI Mac
        if: matrix.os == 'macos-latest'
        run: wget "https://github.com/maidsafe/safe-api/releases/download/${{env.SAFE_CLI_VERSION}}/safe-cli-${{env.SAFE_CLI_VERSION}}-x86_64-apple-darwin.tar.gz" -O ./safe.tar.gz;

      - name: Download Safe CLI Windows
        if: matrix.os == 'windows-latest'
        run: wget "https://github.com/maidsafe/safe-api/releases/download/${{env.SAFE_CLI_VERSION}}/safe-cli-${{env.SAFE_CLI_VERSION}}-x86_64-pc-windows-msvc.tar.gz" -O ./safe.tar.gz;

      - name: Place Safe CLI
        run:  |
          ls .
          mkdir -p $HOME/.safe/safe-cli
          tar -xvzf ./safe.tar.gz -C $HOME/.safe/safe-cli/
          echo "::add-path::$HOME/.safe/safe-cli"
          chmod +x $HOME/.safe/safe-cli/safe

      - name: Check Safe Versions
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run : |
          $HOME/.safe/authd/safe-authd -V
          $HOME/.safe/vault/safe_vault -V
          safe --version
          cat native/Cargo.toml

      # Run tests.
      # Currently do not run client tests on mac
      - name: Cargo tests
        uses: actions-rs/cargo@v1
        if: matrix.os != 'macos-latest'
        with:
          command: test
          args: --release  --features=simulated-payouts

      - name: Basic mac tests
        uses: actions-rs/cargo@v1
        if: matrix.os == 'macos-latest'
        with:
          command: test
          args: --release  

  # list all duplicate dependencies. Note that this does not error if duplicates found
  dependencies:
    name: List Duplicate Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install Rust
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Run list duplicate dependencies script
      - shell: bash
        run: ./scripts/duplicate_dependency_check
